<?php

class ExternalOfficeSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $offices = [
            [
                'name' => 'Capitol Resort Hotel Operations Division',
                'abbreviation' => 'CRHOD',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'General Services Office',
                'abbreviation' => 'GSO',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Human Resource Management and Development Office',
                'abbreviation' => 'HRMDO',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Internal Audit Division',
                'abbreviation' => 'IAD',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Management Information Services Office',
                'abbreviation' => 'MISO',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Pangasinan Polytechnic College',
                'abbreviation' => 'PPC',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Pangasinan Provincial Environment and Natural Resources Office',
                'abbreviation' => 'PPENRO',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Pangasinan Provincial Jail',
                'abbreviation' => 'PPJ',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Pangasinan Public Employment Services Office',
                'abbreviation' => 'PPESO',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Accounting Office',
                'abbreviation' => 'PAcO',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Agriculture Office',
                'abbreviation' => 'PAgO',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Archives and Records Center',
                'abbreviation' => 'PARC',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Assessment Office',
                'abbreviation' => 'PAO',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Board Secretary',
                'abbreviation' => 'PBS',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Budget Office',
                'abbreviation' => 'PBO',
                'sort_order' => 15,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Community Development and Training Office',
                'abbreviation' => 'PCDTO',
                'sort_order' => 16,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Disaster Risk Reduction and Management Office',
                'abbreviation' => 'PDRRMO',
                'sort_order' => 17,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Economic Development and Investment Promotion Office',
                'abbreviation' => 'PEDIPO',
                'sort_order' => 18,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Engineering Office',
                'abbreviation' => 'PEO',
                'sort_order' => 19,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Governor\'s Office',
                'abbreviation' => 'PGO',
                'sort_order' => 20,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Health Office',
                'abbreviation' => 'PHO',
                'sort_order' => 21,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Hospital Management Services Office',
                'abbreviation' => 'PHMSO',
                'sort_order' => 22,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Human Settlements and Urban Development Authority',
                'abbreviation' => 'PHSUDA',
                'sort_order' => 23,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Information Office',
                'abbreviation' => 'PIO',
                'sort_order' => 24,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Legal Office',
                'abbreviation' => 'PLO',
                'sort_order' => 25,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Library Office',
                'abbreviation' => 'PLibO',
                'sort_order' => 26,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Planning and Development Office',
                'abbreviation' => 'PPDO',
                'sort_order' => 27,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Population Cooperative and Livelihood Development Office',
                'abbreviation' => 'PPCLDO',
                'sort_order' => 28,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Social Welfare and Development Office',
                'abbreviation' => 'PSWDO',
                'sort_order' => 29,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Treasurer\'s Office',
                'abbreviation' => 'PTO',
                'sort_order' => 30,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Tourism and Cultural Affairs Office',
                'abbreviation' => 'PTCAO',
                'sort_order' => 31,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Vice Governor\'s Office',
                'abbreviation' => 'PVGO',
                'sort_order' => 32,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Veterinary Office',
                'abbreviation' => 'PVetO',
                'sort_order' => 33,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        $this->insertOrIgnore('external_offices', $offices);

        echo "  Inserted " . count($offices) . " external offices" . PHP_EOL;
    }
}