<?php

class OpinionOfficeSeeder extends Seeder
{
    public function run(): void
    {
        $now = date('Y-m-d H:i:s');

        $offices = [
            [
                'name' => 'Civil Service Commission',
                'abbreviation' => 'CSC',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Department of Agrarian Reform',
                'abbreviation' => 'DAR',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Department of Human Settlements and Urban Development',
                'abbreviation' => 'DHSUD',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Department of the Interior and Local Government',
                'abbreviation' => 'DILG',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Human Resource Management and Development Office',
                'abbreviation' => 'HRMDO',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Local Finance Committee',
                'abbreviation' => 'LFC',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'National Historical Institute of the Philippines',
                'abbreviation' => 'NHIP',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Office of the Provincial Agriculturist',
                'abbreviation' => 'OPAG',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Pangasinan Environment and Natural Resources Office',
                'abbreviation' => 'ENRO',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Accounting Office',
                'abbreviation' => 'PAO',
                'sort_order' => 10,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Health Office',
                'abbreviation' => 'PHO',
                'sort_order' => 11,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Human Settlements and Urban Development Authority',
                'abbreviation' => 'HOUSING',
                'sort_order' => 12,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Legal Office',
                'abbreviation' => 'PLO',
                'sort_order' => 13,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Planning and Development Office',
                'abbreviation' => 'PPDO',
                'sort_order' => 14,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Social Welfare and Development Office',
                'abbreviation' => 'PSWDO',
                'sort_order' => 15,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => 'Provincial Tourism and Cultural Affairs Office',
                'abbreviation' => 'TOURISM',
                'sort_order' => 16,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'name' => "Provincial Treasurer's Office",
                'abbreviation' => 'PTO',
                'sort_order' => 17,
                'is_active' => 1,
                'created_at' => $now,
                'updated_at' => $now,
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        $this->insertOrIgnore('opinion_offices', $offices);

        echo "  Inserted " . count($offices) . " opinion offices" . PHP_EOL;
    }
}